---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myhello-world-app
  namespace: demo-app
spec:
  selector:
    matchLabels:
      app: hello-k8s
  template:
    metadata:
      labels:
        app: hello-k8s
    spec:
      replicas: 1
      containers:
      - name: my-awesome-app
        image: macintoshprime/hello-kubernetes:6e8f2751e4664593f13e520979922be00800ebe8
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"          
          limits:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
          name: http
