---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myhello-world-app
  namespace: demo-app
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.mtapp: glob:dev-*
spec:
  selector:
    matchLabels:
      app: hello-k8s
  template:
    metadata:
      labels:
        app: hello-k8s
    spec:
      containers:
      - name: myapp
        image: macintoshprime/hello-kubernetes:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
          name: http
