---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myhello-world-app
  annotations:
    flux.weave.works/automated: "true"
spec:
  selector:
    matchLabels:
      app: hello-k8s
  template:
    metadata:
      labels:
        app: hello-k8s
    spec:
      containers:
      - name: myapp
        image: macintoshprime/hello-kubernetes:810da9a226a33bb7a5f0bd13f8228316b24c4177
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
          name: http
