---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myhello-world-app
  namespace: demo-app
  annotations:
    flux.weave.works/automated: "true"
spec:
  selector:
    matchLabels:
      app: hello-k8s
  template:
    metadata:
      labels:
        app: hello-k8s
    spec:
      containers:
      - name: myapp
        image: macintoshprime/hello-kubernetes:68dbcb57a43e1b9c9888b8163403a11f7a0edcb3
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
          name: http
