apiVersion: apps/v1
kind: Deployment
metadata:
  name: myhello-world-app
  namespace: hello-k8s
spec:
  selector:
    matchLabels:
      app: hello-k8s
  template:
    metadata:
      labels:
        app: hello-k8s
      namespace: hello-k8s
    spec:
      containers:
      - name: myapp
        image: macintoshprime/hello-kubernetes:v8
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
          name: http
