# example from: https://github.com/kind-ci/examples/blob/master/.github/workflows/kind.yml
name: Kind
on: [push, pull_request]
jobs:

  validation:
    name: Validate manifests
    runs-on: [ubuntu-latest]
    container: macintoshprime/kubectl:v1.17-git
    steps:
    - uses: actions/checkout@v1
    - name: Validate YAML
      run: |
       kubeval --strict -d deploy/

  policy-check:
    name: validate policy
    runs-on: ubuntu-latest
    container: macintoshprime/kubectl:v1.17-git
    steps:
    - name: Deny latest container image tags
        run: |
            pwd
            cd /kubeknife
            mkdir policy
            git clone https://github.com/cartyc/opa-policies.git policy
            conftest test -p policy deploy/

  test-unit:
    name: Create a Kind cluster
    runs-on: [ubuntu-latest]
    needs: validation
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: Install latest version of Kind
      run: |
        GO111MODULE=on go get sigs.k8s.io/kind
    - name: Create Kind cluster
      run: |
        PATH=$(go env GOPATH)/bin:$PATH kind create cluster --config ci-configs/kind-config.yaml
    - name: Run some sanity checks
      # kubectl is already installed on the Github Ubuntu worker
      run: |
        kubectl get nodes -o wide
        kubectl get pods --all-namespaces -o wide
        kubectl get services --all-namespaces -o wide
    - name: Deploy application and test
      run: | 
        kubectl create namespace demo-app
        kubectl apply -f deploy/