name: Policy Validation
on: [push, pull_request]
jobs:
  test-unit:
    name: Create a Kind cluster
    runs-on: [ubuntu-latest]
    container: macintoshprime/kubectl:v1.17-git
    steps:
    - uses: actions/checkout@v1
    - name: Validate YAML
      run: |
       kubeval --strict deploy/